### ISSUE TITLE
Add printf wrappers to libft

### ISSUE THREAD

**Issue by Fulguritude** [LexouDuck/libft#6]
Add some to IO (printf, asprintf and snprintf; and their fd counterparts), and a small wrapper on asprintf called String_Build (ft_strbuild), that returns a `char*` in libft_string

**Comment by LexouDuck** [comment]
done with commits:
506bdeb2354d18f14ae1ee4465eb80786383677a
6a5799e4572c6356127e5b783467ed26f1663205
